/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carrerahilos;

/**
 *
 * @author patriciaaguayo
 */
public class InterfazCarrera extends javax.swing.JFrame {

    /**
     * Creates new form InterfazCarrera
     */
    public InterfazCarrera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Toad = new javax.swing.JLabel();
        Fantasma = new javax.swing.JLabel();
        Donkey = new javax.swing.JLabel();
        Sonic = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Toad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reducida/Toad.png"))); // NOI18N
        getContentPane().add(Toad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        Fantasma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reducida/pacman.png"))); // NOI18N
        getContentPane().add(Fantasma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        Donkey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reducida/donkey.png"))); // NOI18N
        getContentPane().add(Donkey, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        Sonic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reducida/sonic.png"))); // NOI18N
        getContentPane().add(Sonic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 50, 60));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo2.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jProgressBar1.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, 180, 150));

        jProgressBar2.setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 180, 150));

        jProgressBar3.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(jProgressBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 180, 150));

        jProgressBar4.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(jProgressBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 180, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCarrera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Donkey;
    private javax.swing.JLabel Fantasma;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Sonic;
    private javax.swing.JLabel Toad;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    // End of variables declaration//GEN-END:variables
}
